server:
    port: 10000
    servlet:
        session:
            tracking-modes: cookie

spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//15.164.100.115:1521/XE
        username: scott
        password: 1234

    servlet:
      multipart:
          enabled: true
          max-request-size: 40MB
          max-file-size: 10MB
          file-size-threshold: 100MB
          location: ${java.io.tmpdir}
<<<<<<< HEAD
          
=======
>>>>>>> 97bd2e0d62ccb8b62c296b00aa6aa5612d326a10
    mail:
        host: smtp.gmail.com
        port: 587
        username: luna99954
        password: aoqe rrpk dcnd awom
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

mybatis:
    config-location: classpath:/config/config.xml
    mapper-locations: classpath*:/mapper/*.xml
    type-aliases-package: com.app.pickcourse.domain.**

