CREATE SEQUENCE SEQ_SCHEDULE;
CREATE TABLE TBL_SCHEDULE(
                             ID NUMBER CONSTRAINT PK_SCHEDULE PRIMARY KEY,
                             SCHEDULE_CONTENT VARCHAR2(2000) NOT NULL,
                             PLAN_ID NUMBER NOT NULL,
                             CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY(PLAN_ID)
                             REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);
SELECT * FROM TBL_SCHEDULE;
DROP TABLE TBL_SCHEDULE;
DROP SEQUENCE SEQ_SCHEDULE;
