CREATE SEQUENCE SEQ_VOLUNTEER_PARTICIPANT;
CREATE TABLE TBL_VOLUNTEER_PARTICIPANT (
                                 ID NUMBER CONSTRAINT PK_V_PARTICIPANT PRIMARY KEY,
                                 MEMBER_ID NUMBER NOT NULL,
                                 COURSE_ID NUMBER NOT NULL,
                                 CREATED_DATE DATE DEFAULT SYSDATE,
                                 UPDATED_DATE DATE DEFAULT SYSDATE,
                                 CONSTRAINT FK_V_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
                                     REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
                                 CONSTRAINT FK_V_PARTICIPANT_COURSE FOREIGN KEY(COURSE_ID)
                                     REFERENCES TBL_COURSE(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_PARTICIPANT IS '봉사코스의 참여자 정보를 저장하는 테이블';
COMMENT ON COLUMN TBL_VOLUNTEER_PARTICIPANT.ID IS 'TBL_PARTICIPANT의 고유 식별자, 기본 키';
COMMENT ON COLUMN TBL_VOLUNTEER_PARTICIPANT.MEMBER_ID IS '참여자의 회원 ID';
COMMENT ON COLUMN TBL_VOLUNTEER_PARTICIPANT.COURSE_ID IS '참여자가 속한 플랜 ID';
COMMENT ON COLUMN TBL_VOLUNTEER_PARTICIPANT.CREATED_DATE IS '데이터 생성 날짜, 기본값은 SYSDATE';
COMMENT ON COLUMN TBL_VOLUNTEER_PARTICIPANT.UPDATED_DATE IS '데이터 수정 날짜, 기본값은 SYSDATE';

