CREATE SEQUENCE SEQ_WRITE_EXCLUDE;
CREATE TABLE TBL_WRITE_EXCLUDE (
                             ID NUMBER CONSTRAINT PK_WRITE_EXCLUDE PRIMARY KEY,
                             EXCLUDE_CONTENT VARCHAR2(1000) DEFAULT '',
                             PLAN_ID NUMBER NOT NULL,
                             CONSTRAINT FK_EXCLUDE_PLAN FOREIGN KEY (PLAN_ID)
                             REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_WRITE_EXCLUDE;
SELECT * FROM TBL_PLAN;
DROP TABLE TBL_WRITE_EXCLUDE;
DROP TABLE TBL_WRITE_INCLUDE;
DROP TABLE TBL_WRITE_PREPARE;
DROP TABLE TBL_SCHEDULE;
DROP SEQUENCE SEQ_WRITE_EXCLUDE;