CREATE SEQUENCE SEQ_PAY;
CREATE TABLE TBL_PAY(
        ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
        PAY_PRICE NUMBER DEFAULT 0,
        PAY_METHOD VARCHAR2(1000) NOT NULL,
        PAY_CARD_COMPANY VARCHAR2(1000) DEFAULT NULL,
        MEMBER_ID NUMBER NOT NULL,
        PLAN_ID NUMBER NOT NULL,
        CREATE_DATE DATE DEFAULT SYSDATE,
        UPDATE_DATE DATE DEFAULT SYSDATE,
        CONSTRAINT FK_PAY_MEMBER FOREIGN KEY(MEMBER_ID)
        REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
        CONSTRAINT FK_PAY_PLAN FOREIGN KEY(PLAN_ID)
        REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

DROP SEQUENCE SEQ_PAY;
DROP TABLE TBL_PAY;