CREATE SEQUENCE SEQ_QUESTION;
CREATE TABLE TBL_QUESTION (
                              ID NUMBER CONSTRAINT PK_QEUSTION PRIMARY KEY,
                              QUESTION_CONTENT VARCHAR2(1000) NOT NULL,
                              MEMBER_ID NUMBER NOT NULL,
                              PLAN_ID NUMBER NOT NULL,
                              CREATE_DATE DATE DEFAULT SYSDATE,
                              CONSTRAINT FK_QEUSTION_MEMBER FOREIGN KEY(MEMBER_ID)
                                  REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
                              CONSTRAINT FK_QEUSTION_PLAN FOREIGN KEY(PLAN_ID)
                                  REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);
SELECT * FROM TBL_QUESTION
ORDER BY ID DESC ;
DROP TABLE TBL_ANSWER;

SELECT Q.ID, QUESTION_CONTENT, MEMBER_ID, PLAN_ID, CREATE_DATE, M.MEMBER_NICKNAME
FROM TBL_MEMBER M
         JOIN TBL_QUESTION Q
              ON M.ID = Q.MEMBER_ID
WHERE PLAN_ID = 113
ORDER BY ID DESC;