
CREATE TABLE TBL_TOGETHER_FEED (
                                   ID NUMBER CONSTRAINT PK_TOGETHER_FEED PRIMARY KEY,
                                   MEMBER_ID NUMBER NOT NULL,
                                   CONSTRAINT FK_TOGETHER_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
                                   CONSTRAINT FK_TOGETHER_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_TOGETHER_FEED IS '함께하는 피드 테이블';
COMMENT ON COLUMN TBL_TOGETHER_FEED.ID IS '함께하는 피드의 고유 ID';
COMMENT ON COLUMN TBL_TOGETHER_FEED.MEMBER_ID IS '멤버의 고유 ID';