CREATE SEQUENCE SEQ_PARTICIPANT;
CREATE TABLE TBL_PARTICIPANT (
                                 ID NUMBER CONSTRAINT PK_PARTICIPANT PRIMARY KEY,
                                 MEMBER_ID NUMBER NOT NULL,
                                 PLAN_ID NUMBER NOT NULL,
                                 CREATED_DATE DATE DEFAULT SYSDATE,
                                 UPDATED_DATE DATE DEFAULT SYSDATE,
                                 CONSTRAINT FK_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
                                 REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
                                 CONSTRAINT FK_PARTICIPANT_PLAN FOREIGN KEY(PLAN_ID)
                                 REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_PARTICIPANT IS '참여자 정보를 저장하는 테이블';
COMMENT ON COLUMN TBL_PARTICIPANT.ID IS 'TBL_PARTICIPANT의 고유 식별자, 기본 키';
COMMENT ON COLUMN TBL_PARTICIPANT.MEMBER_ID IS '참여자의 회원 ID, TBL_MEMBER 테이블과 외래키 관계';
COMMENT ON COLUMN TBL_PARTICIPANT.PLAN_ID IS '참여자가 속한 플랜 ID, TBL_PLAN 테이블과 외래키 관계';
COMMENT ON COLUMN TBL_PARTICIPANT.CREATED_DATE IS '데이터 생성 날짜, 기본값은 SYSDATE';
COMMENT ON COLUMN TBL_PARTICIPANT.UPDATED_DATE IS '데이터 수정 날짜, 기본값은 SYSDATE';
