CREATE SEQUENCE SEQ_REAL_TAG;
CREATE TABLE TBL_REAL_TAG(
                             ID NUMBER CONSTRAINT PK_REAL_TAG PRIMARY KEY,
                             TAG_CONTENT VARCHAR2(2000) NOT NULL,
                             FEED_ID NUMBER NOT NULL,
                             CONSTRAINT FK_REAL_TAG_FEED FOREIGN KEY(FEED_ID)
                             REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_REAL_TAG IS '실제 피드 태그 테이블';
COMMENT ON COLUMN TBL_REAL_TAG.ID IS '실제 피드 태그의 고유 ID';
COMMENT ON COLUMN TBL_REAL_TAG.TAG_CONTENT IS '태그 내용';
COMMENT ON COLUMN TBL_REAL_TAG.FEED_ID IS '피드의 고유 ID';
