
CREATE TABLE TBL_GENERAL_FILE (
      ID NUMBER CONSTRAINT PK_GENERAL_FILE PRIMARY KEY,
      FEED_ID NUMBER NOT NULL,
      CONSTRAINT FK_GENERAL_FILE_FILE FOREIGN KEY(ID) REFERENCES TBL_FILE(ID) ON DELETE CASCADE ,
      CONSTRAINT FK_GENERAL_FILE_GENERAL_FEED FOREIGN KEY(FEED_ID) REFERENCES TBL_GENERAL_FEED(ID) ON DELETE CASCADE
);

COMMENT ON TABLE TBL_GENERAL_FILE IS '일반 피드 파일 테이블';
COMMENT ON COLUMN TBL_GENERAL_FILE.ID IS '일반 파일의 고유 ID';
COMMENT ON COLUMN TBL_GENERAL_FILE.FEED_ID IS '일반 피드의 고유 ID';