CREATE SEQUENCE SEQ_NOTICE;
CREATE TABLE TBL_NOTICE(
                           ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
                           NOTICE_TITLE VARCHAR2(1000) NOT NULL,
                           NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
                           ADMIN_ID NUMBER NOT NULL,
                           CREATED_DATE DATE DEFAULT SYSDATE,
                           UPDATED_DATE DATE DEFAULT SYSDATE,
                           CONSTRAINT FK_NOTICE_ADMIN FOREIGN KEY(ADMIN_ID)
                           REFERENCES TBL_ADMIN(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_NOTICE IS '공지사항 테이블';
COMMENT ON COLUMN TBL_NOTICE.ID IS '고유 식별자';
COMMENT ON COLUMN TBL_NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN TBL_NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN TBL_NOTICE.ADMIN_ID IS '관리자 ID (외래 키)';
COMMENT ON COLUMN TBL_NOTICE.CREATED_DATE IS '생성 날짜 (기본값: 현재 날짜)';
COMMENT ON COLUMN TBL_NOTICE.UPDATED_DATE IS '수정 날짜 (기본값: 현재 날짜)';