CREATE SEQUENCE SEQ_GENERAL_TAG;
CREATE TABLE TBL_GENERAL_TAG(
                                ID NUMBER CONSTRAINT PK_GENERAL_TAG PRIMARY KEY,
                                TAG_CONTENT VARCHAR2(2000) NOT NULL,
                                FEED_ID NUMBER NOT NULL,
                                CONSTRAINT FK_GENERAL_TAG_FEED FOREIGN KEY(FEED_ID)
                                    REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_GENERAL_TAG IS '일반 피드 태그 테이블';
COMMENT ON COLUMN TBL_GENERAL_TAG.ID IS '일반 피드 태그의 고유 ID';
COMMENT ON COLUMN TBL_GENERAL_TAG.TAG_CONTENT IS '태그 내용';
COMMENT ON COLUMN TBL_GENERAL_TAG.FEED_ID IS '피드의 고유 ID';