
CREATE TABLE TBL_GENERAL_REPLY(
                                  ID NUMBER CONSTRAINT PK_GENERAL_REPLY PRIMARY KEY,
                                  MEMBER_ID NUMBER NOT NULL,
                                  FEED_ID NUMBER NOT NULL,
                                  CONSTRAINT FK_GENERAL_REPLY_REPLY FOREIGN KEY(ID)
                                  REFERENCES TBL_REPLY(ID) ON DELETE CASCADE ,
                                  CONSTRAINT FK_GENERAL_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
                                  REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
                                  CONSTRAINT FK_GENERAL_REPLY_GENERAL_FEED FOREIGN KEY(FEED_ID)
                                  REFERENCES TBL_GENERAL_FEED(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_GENERAL_REPLY IS '일반 피드 댓글 테이블';
COMMENT ON COLUMN TBL_GENERAL_REPLY.ID IS '일반 피드 댓글의 고유 ID';
COMMENT ON COLUMN TBL_GENERAL_REPLY.MEMBER_ID IS '멤버의 고유 ID';
COMMENT ON COLUMN TBL_GENERAL_REPLY.FEED_ID IS '일반 피드의 고유 ID';