CREATE SEQUENCE SEQ_PATH;
CREATE TABLE TBL_PATH(
                         ID NUMBER CONSTRAINT PK_ID PRIMARY KEY,
                         PATH_NAME VARCHAR2(1000) NOT NULL,
                         PATH_ADDRESS VARCHAR(1000) NOT NULL,
                         COURSE_ID NUMBER NOT NULL,
                         CREATED_DATE DATE DEFAULT SYSDATE,
                         UPDATED_DATE DATE DEFAULT SYSDATE,
                         CONSTRAINT FK_PATH_COURSE FOREIGN KEY(COURSE_ID)
                         REFERENCES TBL_COURSE(ID)  ON DELETE CASCADE
);
COMMENT ON COLUMN TBL_PATH.ID IS '경로의 고유 ID (기본 키)';
COMMENT ON COLUMN TBL_PATH.PATH_NAME IS '경로 이름';
COMMENT ON COLUMN TBL_PATH.PATH_ADDRESS IS '경로 주소';
COMMENT ON COLUMN TBL_PATH.COURSE_ID IS '연결된 코스의 ID (외래 키)';
COMMENT ON COLUMN TBL_PATH.CREATED_DATE IS '레코드 생성 날짜 (기본값: SYSDATE)';
COMMENT ON COLUMN TBL_PATH.UPDATED_DATE IS '레코드 수정 날짜 (기본값: SYSDATE)';

