CREATE TABLE TBL_REPLY_REPORT(
                          ID NUMBER CONSTRAINT PK_REPLY_REPORT PRIMARY KEY,
                          REPORTED_REASON VARCHAR2(200),
                          REPORTED_ID  NUMBER NOT NULL,
                          MEMBER_ID NUMBER NOT NULL,
                          CREATED_DATE DATE DEFAULT SYSDATE,
                          UPDATED_DATE DATE DEFAULT SYSDATE,
                          CONSTRAINT FK_REPLY_REPORT_REPORT FOREIGN KEY(ID) REFERENCES TBL_REPORT(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_REPLY_REPORT_REPLY FOREIGN KEY(REPORTED_ID) REFERENCES TBL_REPLY(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_REPLY_REPORT_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_REPLY_REPORT IS '댓글 신고 테이블';
COMMENT ON COLUMN TBL_REPLY_REPORT.ID IS '댓글 신고의 고유 ID';
COMMENT ON COLUMN TBL_REPLY_REPORT.REPORTED_REASON IS '신고 이유';
COMMENT ON COLUMN TBL_REPLY_REPORT.REPORTED_ID IS '댓글 ID';
COMMENT ON COLUMN TBL_REPLY_REPORT.MEMBER_ID IS '신고한 회원의 고유 ID';
COMMENT ON COLUMN TBL_REPLY_REPORT.CREATED_DATE IS '생성 날짜';
COMMENT ON COLUMN TBL_REPLY_REPORT.UPDATED_DATE IS '수정 날짜';