CREATE SEQUENCE SEQ_REAL_FEED;
CREATE TABLE TBL_REAL_FEED (
                               ID NUMBER CONSTRAINT PK_REAL_FEED PRIMARY KEY,
                               MEMBER_ID NUMBER NOT NULL,
                               PLAN_ID NUMBER NOT NULL,
                               CONSTRAINT FK_REAL_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
                               CONSTRAINT FK_REAL_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE,
                               CONSTRAINT FK_REAL_FEED_PLAN FOREIGN KEY(PLAN_ID) REFERENCES TBL_PLAN(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_REAL_FEED IS '실제 피드 테이블';
COMMENT ON COLUMN TBL_REAL_FEED.ID IS '실제 피드의 고유 ID';
COMMENT ON COLUMN TBL_REAL_FEED.MEMBER_ID IS '멤버의 고유 ID';
COMMENT ON COLUMN TBL_REAL_FEED.PLAN_ID IS '계획의 고유 ID';