CREATE SEQUENCE SEQ_SCHEDULE;
CREATE TABLE TBL_SCHEDULE(
                             ID NUMBER CONSTRAINT PK_SCHEDULE PRIMARY KEY,
                             SCHEDULE_CONTENT VARCHAR2(2000) NOT NULL,
                             PLAN_ID NUMBER NOT NULL,
                             CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY(PLAN_ID)
                             REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);
SELECT * FROM TBL_SCHEDULE
ORDER BY ID DESC ;
SELECT * FROM TBL_WRITE_PREPARE
ORDER BY ID DESC ;
SELECT * FROM TBL_PLAN
    WHERE ID = 112;
DROP TABLE TBL_SCHEDULE;
DROP SEQUENCE SEQ_SCHEDULE;

ALTER TABLE TBL_SCHEDULE
    ADD STATUS VARCHAR2(1000) DEFAULT 'ENABLE';
