
CREATE TABLE TBL_REPLY_REPORT(
                          ID NUMBER CONSTRAINT PK_REPLY_REPORT PRIMARY KEY,
                          REPLY_ID NUMBER NOT NULL,
                          MEMBER_ID NUMBER NOT NULL,
                          CREATE_DATE DATE DEFAULT SYSDATE,
                          UPDATE_DATE DATE DEFAULT SYSDATE,
                          CONSTRAINT FK_REPLY_REPORT_REPORT FOREIGN KEY(ID) REFERENCES TBL_REPORT(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_REPLY_REPORT_REPLY FOREIGN KEY(REPLY_ID) REFERENCES TBL_REPLY(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_REPLY_REPORT_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_REPLY_REPORT IS '댓글 신고 테이블';
COMMENT ON COLUMN TBL_REPLY_REPORT.ID IS '댓글 신고의 고유 ID';
COMMENT ON COLUMN TBL_REPLY_REPORT.CREATE_DATE IS '생성 날짜';
COMMENT ON COLUMN TBL_REPLY_REPORT.UPDATE_DATE IS '수정 날짜';
COMMENT ON COLUMN TBL_REPLY_REPORT.REPLY_ID IS 'REPLY의 고유 ID';
COMMENT ON COLUMN TBL_REPLY_REPORT.MEMBER_ID IS '멤버의 고유 ID';