CREATE TABLE TBL_FEED_REPORT(
                          ID NUMBER CONSTRAINT PK_FEED_REPORT PRIMARY KEY,
                          REPORTED_REASON VARCHAR2(200),
                          REPORTED_ID  NUMBER NOT NULL,
                          MEMBER_ID NUMBER NOT NULL,
                          CREATED_DATE DATE DEFAULT SYSDATE,
                          UPDATED_DATE DATE DEFAULT SYSDATE,
                          CONSTRAINT FK_FEED_REPORT_REPORT FOREIGN KEY(ID) REFERENCES TBL_REPORT(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_FEED_REPORT_FEED FOREIGN KEY(REPORTED_ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
                          CONSTRAINT FK_FEED_REPORT_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_FEED_REPORT IS '피드 신고 테이블';
COMMENT ON COLUMN TBL_FEED_REPORT.ID IS '피드 신고의 고유 ID';
COMMENT ON COLUMN TBL_FEED_REPORT.REPORTED_REASON IS '신고 이유';
COMMENT ON COLUMN TBL_FEED_REPORT.REPORTED_ID IS 'FEED ID';
COMMENT ON COLUMN TBL_FEED_REPORT.MEMBER_ID IS '신고한 회원의 고유 ID';
COMMENT ON COLUMN TBL_FEED_REPORT.CREATED_DATE IS '생성 날짜';
COMMENT ON COLUMN TBL_FEED_REPORT.UPDATED_DATE IS '수정 날짜';