
CREATE TABLE TBL_GENERAL_FEED (
      ID NUMBER CONSTRAINT PK_GENERAL_FEED PRIMARY KEY,
      MEMBER_ID NUMBER NOT NULL,
      CONSTRAINT FK_GENERAL_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
      CONSTRAINT FK_GENERAL_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

COMMENT ON TABLE TBL_GENERAL_FEED IS '일반 피드 테이블';
COMMENT ON COLUMN TBL_GENERAL_FEED.ID IS '일반 피드의 고유 ID';
COMMENT ON COLUMN TBL_GENERAL_FEED.MEMBER_ID IS '멤버의 고유 ID';