CREATE SEQUENCE SEQ_REPORT;
CREATE TABLE TBL_REPORT(
                          ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
                          CREATED_DATE DATE DEFAULT SYSDATE,
                          UPDATED_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE TBL_REPORT IS '신고 테이블';
COMMENT ON COLUMN TBL_REPORT.ID IS '신고의 고유 ID';
COMMENT ON COLUMN TBL_REPORT.CREATED_DATE IS '생성 날짜';
COMMENT ON COLUMN TBL_REPORT.UPDATED_DATE IS '수정 날짜';