CREATE SEQUENCE SEQ_PARTICIPANT;
CREATE TABLE TBL_PARTICIPANT (
                                 ID NUMBER CONSTRAINT PK_PARTICIPANT PRIMARY KEY,
                                 MEMBER_ID NUMBER NOT NULL,
                                 PLAN_ID NUMBER NOT NULL,
                                 CREATED_DATE DATE DEFAULT SYSDATE,
                                 UPDATED_DATE DATE DEFAULT SYSDATE,
                                 CONSTRAINT FK_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
                                 REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
                                 CONSTRAINT FK_PARTICIPANT_PLAN FOREIGN KEY(PLAN_ID)
                                 REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);
COMMENT ON TABLE TBL_PARTICIPANT IS '참여자 정보를 저장하는 테이블';
COMMENT ON COLUMN TBL_PARTICIPANT.ID IS 'TBL_PARTICIPANT의 고유 식별자, 기본 키';
COMMENT ON COLUMN TBL_PARTICIPANT.MEMBER_ID IS '참여자의 회원 ID, TBL_MEMBER 테이블과 외래키 관계';
COMMENT ON COLUMN TBL_PARTICIPANT.PLAN_ID IS '참여자가 속한 플랜 ID, TBL_PLAN 테이블과 외래키 관계';
COMMENT ON COLUMN TBL_PARTICIPANT.CREATED_DATE IS '데이터 생성 날짜, 기본값은 SYSDATE';
COMMENT ON COLUMN TBL_PARTICIPANT.UPDATED_DATE IS '데이터 수정 날짜, 기본값은 SYSDATE';


SELECT * FROM TBL_ADMIN;
SELECT * FROM TBL_COURSE;
SELECT * FROM TBL_PLAN;

INSERT INTO TBL_ADMIN (ID, ADMIN_ACCOUNT, ADMIN_PASSWORD, ADMIN_NAME, ADMIN_PHONE, ADMIN_EMAIL)
VALUES (SEQ_COURSE.NEXTVAL, 'admin1', '1234', '관리자', '010-1111-1111', 'admin@test.com');


INSERT INTO TBL_COURSE (ID, COURSE_TYPE, COURSE_IS_VOLUNTEER, COURSE_NAME, COURSE_DISTANCE, COURSE_SCHEDULE, COURSE_THEME, COURSE_CONTENT, ADMIN_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_COURSE.NEXTVAL, '일반', 'N', '테스트 코스', '10km', '2025-03-21', '자연', '테스트 코스 설명', 12, SYSDATE, SYSDATE);

INSERT INTO TBL_PLAN (ID, COURSE_ID, PLAN_NAME, PLAN_START_DATE, PLAN_END_DATE, PLAN_DEADLINE, PLAN_MAX_PERSONNEL, PLAN_MIN_PERSONNEL, PLAN_PRICE, PLAN_START_ADDRESS, PLAN_CONTENT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_PLAN.NEXTVAL, 16, '테스트 플랜', SYSDATE, SYSDATE + 1, SYSDATE - 1, 10, 1, 50000, '서울', '테스트 플랜 설명', 1, SYSDATE, SYSDATE);

INSERT INTO TBL_PARTICIPANT (ID, MEMBER_ID, PLAN_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_PARTICIPANT.NEXTVAL, 1, 5, SYSDATE, SYSDATE);

SELECT COUNT(*)
FROM TBL_PARTICIPANT P
         JOIN TBL_PLAN PL ON P.PLAN_ID = PL.ID
         JOIN TBL_COURSE C ON PL.COURSE_ID = C.ID
WHERE P.MEMBER_ID = 1
  AND C.COURSE_IS_VOLUNTEER = 'N';

SELECT * FROM TBL_PARTICIPANT WHERE MEMBER_ID = 1;

SELECT * FROM TBL_PLAN WHERE ID IN (SELECT PLAN_ID FROM TBL_PARTICIPANT WHERE MEMBER_ID = 1);

SELECT * FROM TBL_COURSE WHERE ID IN (SELECT COURSE_ID FROM TBL_PLAN WHERE ID IN (SELECT PLAN_ID FROM TBL_PARTICIPANT WHERE MEMBER_ID = 1));



