#GET http://52.78.155.144:10000/admin/course-list?page=1&type=&keyWord=
#Accept: application/json

#GET http://52.78.155.144:10000/admin/course-detail/3
GET http://52.78.155.144:10000/admin/course-type-detail/3