#GET http://43.203.69.19:10000/admin/course-list?page=1&type=&keyWord=
#Accept: application/json

#GET http://43.203.69.19:10000/admin/course-detail/3
GET http://43.203.69.19:10000/admin/course-type-detail/3